/* Fight Arena v0.9.5.4 — Phase 2 Raw Power progression */
(()=>{
'use strict';
const $=id=>document.getElementById(id),controls=()=>window.FightArenaCampaignControls;
const STANDBY=['Ultron','Prowler'];
const DETAILS={
 Nightfang:{lesson:'BASICS',tip:'Move, Punch, Kick and build your Special meter.',abilities:['Shadow Jab','Quick Rush'],reward:'150 🪙 • 25 XP'},
 Voltage:{lesson:'RANGED AWARENESS',tip:'Close distance through Spark Shots and punish his Static Dash.',abilities:['Spark Shot','Static Dash','Shock Pulse'],reward:'200 🪙 • 35 XP'},
 Razor:{lesson:'BLOCK & TIMING',tip:'His pressure is fast. Block the rush, then counter before he resets.',abilities:['Twin Slash','Razor Leap','Spin Cut'],reward:'250 🪙 • 45 XP'},
 Titan:{lesson:'SPACING & PATIENCE',tip:'Titan is slow but dangerous. Bait his heavy attacks and punish recovery.',abilities:['Heavy Smash','Armored Charge','Ground Slam'],reward:'300 🪙 • 60 XP'},
 'Arena Champion':{lesson:'FINAL EXAM',tip:'Use everything you learned. At 45% HP he activates Champion Mode.',abilities:['Champion Strike','Victory Rush','Shockwave Kick','Crown of the Arena'],reward:'500 🪙 • 100 XP • 5 💎 + Phase Reward'},
 Crossbones:{lesson:'TACTICAL PRESSURE',tip:'Rumlow mixes heavy rushes with gunfire. Stay mobile at range and punish committed melee attacks.',abilities:['Skull Breaker','Tactical Burst','Blade Gauntlet','Bones of War'],reward:'350 🪙 • 75 XP'},
 Bullseye:{lesson:'PRECISION CONTROL',tip:'Bullseye wants you predictable. Change your rhythm, close distance carefully and punish Assassin Step.',abilities:['Deadeye Throw','Ricochet Trick','Assassin Step','Perfect Aim'],reward:'450 🪙 • 90 XP'},
 Punisher:{lesson:'ARSENAL MANAGEMENT',tip:'Castle mixes sustained fire, explosives and sudden close-range pressure. Defeat him to unlock Punisher in your Collection.',abilities:['Rifle Burst','Frag Grenade','Combat Roll','War Zone'],reward:'550 🪙 • 110 XP • 🔓 PUNISHER'},
 Taskmaster:{lesson:'ADAPTATION',tip:'Read the weapon in his hands. Shield, sword and bow each demand a different answer.',abilities:['Shield Throw','Sword Rush','Hawkeye Shot','Combat Masterclass'],reward:'650 🪙 • 130 XP'},
 Kingpin:{lesson:'PHASE BOSS',tip:'Survive Kingpin’s raw pressure and Rage phase to open the Sinister Threat.',abilities:['Heavy Punch','Charge Rush','Ground Smash','Kingpin Rage'],reward:'600 🪙 • 150 XP • 5 💎'},
 Rhino:{lesson:'MOMENTUM CONTROL',tip:'Do not trade head-on. Read the charge lane, move out of the line and punish Rhino after his armor commits.',abilities:['Rhino Charge','Horn Toss','Ground Quake','Stampede'],reward:'750 🪙 • 150 XP'},
 Electro:{lesson:'MOBILITY UNDER FIRE',tip:'Yellow lightning owns the range. Keep moving through Arc Bolts and escape the target marker before Power Grid lands.',abilities:['Arc Bolt','Volt Blink','Chain Lightning','Power Grid'],reward:'800 🪙 • 165 XP'}
};
const PHASES=[
 {id:'prologue',eyebrow:'PROLOGUE',title:'NEO CITY ARENA',subtitle:'Five original Fight Arena encounters • beginner journey',theme:'prologue',sections:[{name:'FIRST BLOOD',fights:[{name:'Nightfang',slot:1,built:true}]},{name:'ARENA TRIALS',fights:[{name:'Voltage',slot:2,built:true},{name:'Razor',slot:3,built:true}]},{name:'FINAL QUALIFIERS',final:true,fights:[{name:'Titan',slot:4,built:true},{name:'Arena Champion',slot:5,built:true,boss:true}]}]},
 {id:'phase1',eyebrow:'PHASE 1',title:'STREET CRIMINALS',subtitle:'Grounded criminals, mercenaries and vigilantes',theme:'street',sections:[{name:'STREET WAR',fights:[{name:'Crossbones',slot:1,built:true},{name:'Bullseye',slot:2,built:true}]},{name:'VIGILANTE LINE',fights:[{name:'Punisher',slot:3,built:true,reward:'PLAYABLE FIGHTER UNLOCK'},{name:'Taskmaster',slot:4,built:true}]},{name:'CRIMINAL EMPIRE',final:true,fights:[{name:'Kingpin',slot:5,built:true,boss:true}]}]},
 {id:'phase2',eyebrow:'PHASE 2',title:'SINISTER THREAT',subtitle:'Spider-Man villains escalate from raw power to illusion and chaos',theme:'sinister',sections:[{name:'RAW POWER',fights:[{name:'Rhino',slot:1,built:true},{name:'Electro',slot:2,built:true}]},{name:'SMOKE & CHAOS',fights:[{name:'Mysterio',slot:3,built:true,assigned:true},{name:'Green Goblin',slot:4,built:true,assigned:true}]},{name:'MASTER PLAN',final:true,fights:[{name:'Doctor Octopus',slot:5,boss:true}]}]}
];
let selected=null,ready=false;
const won=n=>!!controls()?.won?.(n),prologueOrder=['Nightfang','Voltage','Razor','Titan','Arena Champion'],phase1Order=['Crossbones','Bullseye','Punisher','Taskmaster','Kingpin'],phase2Order=['Rhino','Electro'];
function prologueAvailable(name){const i=prologueOrder.indexOf(name);return i>=0&&(i===0||won(prologueOrder[i-1]))}
function prologueComplete(){return prologueOrder.every(won)}
function phase1Available(name){const i=phase1Order.indexOf(name);if(i<0||!prologueComplete())return false;return i===0||won(phase1Order[i-1])}
function phase1Complete(){return phase1Order.every(won)}
function phase2Available(name){const i=phase2Order.indexOf(name);if(i<0||!phase1Complete())return false;return i===0||won(phase2Order[i-1])}
function rawPowerComplete(){return phase2Order.every(won)}
function nextTarget(){const p=prologueOrder.find(n=>!won(n));if(p)return p;const s=phase1Order.find(n=>!won(n));if(s)return s;const r=phase2Order.find(n=>!won(n));return r||'Mysterio'}
function statusFor(f){if(f.phase.id==='prologue'){if(won(f.name))return'CLEARED';return prologueAvailable(f.name)?'READY':'LOCKED'}if(f.phase.id==='phase1'&&f.built){if(won(f.name))return'CLEARED';return phase1Available(f.name)?'READY':'LOCKED'}if(f.phase.id==='phase2'&&phase2Order.includes(f.name)){if(won(f.name))return'CLEARED';return phase2Available(f.name)?'READY':'LOCKED'}if(f.assigned)return rawPowerComplete()?'NEXT SECTION':'ASSIGNED';return'COMING SOON'}
function canFight(f){if(!f.built)return false;if(f.phase.id==='prologue')return prologueAvailable(f.name);if(f.phase.id==='phase1')return phase1Available(f.name);if(f.phase.id==='phase2'&&phase2Order.includes(f.name))return phase2Available(f.name);return false}
function setProfile(f=null){const start=$('start');if(!f){const n=nextTarget();$('diff').textContent='v0.9.5.4 • RAW POWER';$('levelTitle').textContent=!prologueComplete()?'PROLOGUE — NEO CITY ARENA':!phase1Complete()?'PHASE 1 — STREET CRIMINALS':!rawPowerComplete()?'PHASE 2 — SINISTER THREAT':'RAW POWER CLEARED';$('levelDesc').textContent=!prologueComplete()?'Complete the five-fight Neo City Arena Prologue to unlock Phase 1.':!phase1Complete()?'Clear Street Criminals and defeat Kingpin to unlock Phase 2.':!rawPowerComplete()?'Rhino and Electro open Sinister Threat with two completely different power fights.':'Mysterio and Green Goblin are preserved as the next Section while Doctor Octopus remains the planned Phase Boss.';$('levelStats').innerHTML=`<div><small>PROLOGUE</small>${prologueOrder.filter(won).length}/5</div><div><small>PHASE 1</small>${phase1Order.filter(won).length}/5</div><div><small>RAW POWER</small>${phase2Order.filter(won).length}/2</div><div><small>NEXT</small>${n.toUpperCase()}</div>`;if(start){start.disabled=true;start.textContent='SELECT A FIGHT'}return}
 const d=DETAILS[f.name],status=statusFor(f);$('diff').textContent=`${f.phase.eyebrow} • ${f.section.name}`;$('levelTitle').textContent=`FIGHT ${f.slot} — ${f.name.toUpperCase()}`;
 if(d){$('levelDesc').textContent=d.tip;$('levelStats').innerHTML=`<div><small>LESSON</small>${d.lesson}</div><div><small>STATUS</small>${status}</div><div><small>REWARD</small>${d.reward}</div><div><small>${f.boss?'BOSS':'ABILITIES'}</small>${f.boss?'FINAL FIGHT':d.abilities.length+' MOVES'}</div>`}else{$('levelDesc').textContent=f.assigned?`${f.name} already exists in Fight Arena and is preserved for the next Sinister Threat Section.`:'This encounter is reserved for a future v0.9.5.x build.';$('levelStats').innerHTML=`<div><small>PHASE</small>${f.phase.eyebrow}</div><div><small>SLOT</small>${f.slot}/5</div><div><small>TYPE</small>${f.boss?'PHASE BOSS':'STANDARD'}</div><div><small>STATUS</small>${status}</div>`}
 if(start){const go=canFight(f);start.disabled=!go;start.textContent=go?(won(f.name)?`REPLAY ${f.name.toUpperCase()}`:`FIGHT ${f.name.toUpperCase()}`):status==='LOCKED'?'BEAT PREVIOUS FIGHT':status==='CLEARED'?`REPLAY ${f.name.toUpperCase()}`:'COMING SOON';if(status==='CLEARED'&&f.built)start.disabled=false;start.onclick=()=>{if(f.built&&canFight(f))controls()?.start?.(f.name)}}
 let extra=$('campaignLessonPanel');if(!extra){extra=document.createElement('div');extra.id='campaignLessonPanel';extra.className='campaign-lesson-panel';$('levelStats')?.insertAdjacentElement('afterend',extra)}if(d)extra.innerHTML=`<small>ENCOUNTER KIT</small><div>${d.abilities.map(a=>`<span>${a}</span>`).join('')}</div>${f.name==='Punisher'?'<b>🔓 DEFEAT PUNISHER • PLAYABLE FIGHTER UNLOCK</b>':f.name==='Rhino'?'<b>🦏 ARMORED MOMENTUM • DO NOT TRADE HEAD-ON</b>':f.name==='Electro'?'<b>⚡ 45% HP • ELECTRO ENTERS OVERCHARGE</b>':f.name==='Taskmaster'?'<b>☠ PHOTOGRAPHIC REFLEXES • MULTI-WEAPON MASTER</b>':f.boss?'<b>🏆 PHASE BOSS</b>':''}`;else extra.innerHTML='<small>ROADMAP SLOT</small><div><span>Build pending</span><span>Existing data preserved</span></div>'}
function render(){const box=$('levelCards');if(!box)return;box.innerHTML='';box.className='campaign-phase-list';PHASES.forEach(phase=>{const all=phase.sections.flatMap(s=>s.fights),cleared=phase.id==='prologue'?all.filter(f=>won(f.name)).length:phase.id==='phase1'?phase1Order.filter(won).length:phase.id==='phase2'?phase2Order.filter(won).length:0,article=document.createElement('article');article.className=`campaign-phase phase-${phase.theme} ${phase.id==='phase2'&&!phase1Complete()?'future-phase':''}`;const phaseLabel=phase.id==='prologue'?`${cleared}/5 CLEARED`:phase.id==='phase1'?`${cleared}/5 CLEARED`:phase1Complete()?`${cleared}/2 RAW POWER`:'LOCKED';article.innerHTML=`<div class="phase-head"><div><small>${phase.eyebrow}</small><h3>${phase.title}</h3></div><div class="phase-meta"><b>${phaseLabel}</b><span>${phase.subtitle}</span></div></div>`;phase.sections.forEach((section,si)=>{const sec=document.createElement('section');sec.className=`phase-section ${section.final?'final-section':''}`;const live=phase.id==='phase2'&&section.name==='RAW POWER'?'<span class="raw-power-live">● NEW • v0.9.5.4</span>':phase.id==='phase1'&&section.name==='VIGILANTE LINE'?'<span class="vigilante-live">✓ LIVE</span>':`<span>${section.fights.length} FIGHT${section.fights.length===1?'':'S'}</span>`;sec.innerHTML=`<div class="section-title"><div><small>SECTION ${String(si+1).padStart(2,'0')}</small><b>${section.name}</b></div>${live}</div><div class="phase-fights"></div>`;const grid=sec.querySelector('.phase-fights');section.fights.forEach(base=>{const f={...base,phase,section},status=statusFor(f),d=DETAILS[f.name],b=document.createElement('button');b.type='button';b.className=`campaign-node ${f.boss?'boss ':''}${status==='READY'?'ready ':''}${status==='CLEARED'?'cleared ':''}${status==='LOCKED'?'locked ':''}${f.assigned?'assigned ':''}${selected===f.name?'selected ':''}`;b.innerHTML=`<div class="node-top"><span class="node-number">FIGHT ${f.slot}</span><span class="node-state">${status}</span></div><strong>${f.name.toUpperCase()}</strong><p>${d?`${d.lesson} • ${d.abilities.slice(0,2).join(' + ')}`:f.assigned?'Existing encounter preserved for the next Section':'Reserved roadmap encounter'}</p>${f.reward?`<span class="node-reward">🔓 ${f.reward}</span>`:''}`;b.onclick=()=>{selected=f.name;render();setProfile(f)};grid.appendChild(b)});article.appendChild(sec)});box.appendChild(article)});updateDashboard()}
function updateDashboard(){const n=nextTarget();if($('dashTarget'))$('dashTarget').textContent=n.toUpperCase();if($('dashLevel'))$('dashLevel').textContent=!prologueComplete()?`Prologue • ${prologueOrder.indexOf(n)+1}/5`:!phase1Complete()?`Phase 1 • ${phase1Order.indexOf(n)+1}/5`:!rawPowerComplete()?`Phase 2 • ${phase2Order.indexOf(n)+1}/5`:'Phase 2 • Smoke & Chaos';const latest=document.querySelector('.latest-stat');if(latest){latest.querySelector('b').textContent='v0.9.5.4';latest.querySelector('span').textContent='Rhino • Electro • Raw Power'}}
function versionUI(){document.title='Fight Arena v0.9.5.4 — Raw Power';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.5.4');const hero=document.querySelector('#home .hero-copy');if(hero){hero.querySelector('.tag').textContent='PHASE 2 • RAW POWER';hero.querySelector('h1').innerHTML='THE SINISTER THREAT<br>HITS HARD.';hero.querySelector('p').textContent='Rhino and Electro launch Phase 2 with cinematic armor, living electricity and two radically different combat styles.'}if($('updates'))$('updates').textContent='📋 UPDATE LOG • v0.9.5.4';const health=document.querySelector('.build-health b');if(health)health.textContent='RAW POWER CORE • v0.9.5.4';const chooser=document.querySelector('#deviceChooser .eyebrow');if(chooser)chooser.textContent='FIGHT ARENA v0.9.5.4'}
function refreshAfterNav(){setTimeout(()=>{selected=null;render();setProfile()},0)}
function init(){if(ready)return;ready=true;versionUI();render();setProfile();$('play')?.addEventListener('click',refreshAfterNav);$('continue')?.addEventListener('click',refreshAfterNav);if($('rematch'))$('rematch').onclick=()=>controls()?.rematch?.();window.FightArenaCampaignV0954={ok:true,phases:PHASES,standby:[...STANDBY],render,prologueComplete,phase1Complete,rawPowerComplete}}
if(window.FightArena?.version==='0.9.5.4')setTimeout(init,0);else addEventListener('fightarena-ready',()=>setTimeout(init,0),{once:true});
})();
