/* Multiverse Arena v0.9.5.7.2 — Combat Polish & Immersion */
(()=>{
'use strict';
const BUILD='0.9.5.7.2';
const HERO_INTROS={
 'SPIDER-MAN':['WEB-SLINGER ONLINE','Spidey lands light, fast and ready to move.'],
 'IRON MAN':['SYSTEMS ONLINE','Repulsors charged. Flight systems standing by.'],
 'WOLVERINE':['CLAWS OUT','Regeneration active. Berserker pressure incoming.'],
 'BLACK PANTHER':['WAKANDA FOREVER','Kinetic weave armed. Precision before power.'],
 'CAPTAIN AMERICA':['I CAN DO THIS ALL DAY','Shield ready. Hold the line.'],
 'DAREDEVIL':['THE DEVIL IS LISTENING','Radar sense locked onto every movement.'],
 'MOON KNIGHT':['VENGEANCE ARRIVES','Khonshu watches the arena.'],
 'PUNISHER':['NO SECOND CHANCES','Frank Castle enters fully loaded.'],
 'EL PRIMO':['SHOWTIME','The arena is about to get loud.'],
 'ROOKIE':['PROVE YOURSELF','Every legend starts somewhere.']
};
let lastFightKey='',lastBossPhase=0,lastActive='';
function $(s,r=document){return r.querySelector(s)}
function all(s,r=document){return [...r.querySelectorAll(s)]}
function sfx(kind){window.MultiverseArenaUI?.click?.(kind||'tap')}
function cleanName(t=''){return t.trim().toUpperCase()}
function renameGauntlet(){const play=$('#play');if(play)play.textContent='⚔️ VILLAIN GAUNTLET';all('button').forEach(b=>{if(/PLAY CAMPAIGN/i.test(b.textContent))b.textContent=b.textContent.replace(/PLAY CAMPAIGN/i,'VILLAIN GAUNTLET');if(/^CAMPAIGN$/i.test(b.textContent.trim()))b.textContent='VILLAIN GAUNTLET'});const level=$('#levels .sectionhead h2');if(level)level.textContent='VILLAIN GAUNTLET';const e=$('#levels .sectionhead .eyebrow');if(e)e.textContent='PATH OF THE MULTIVERSE';}
function arenaAtmosphere(){const arena=$('#arena');if(!arena||arena.querySelector('.arena-atmosphere'))return;const layer=document.createElement('div');layer.className='arena-atmosphere';layer.innerHTML='<i class="amb amb-a"></i><i class="amb amb-b"></i><i class="amb amb-c"></i><i class="amb amb-d"></i><span class="arena-haze"></span>';arena.prepend(layer)}
function versusIntro(){const fight=$('#fight');if(!fight?.classList.contains('active'))return;const hero=cleanName($('#pname')?.textContent),enemy=cleanName($('#ename')?.textContent);if(!hero||!enemy)return;const key=hero+'|'+enemy;if(key===lastFightKey)return;lastFightKey=key;document.querySelector('.versus-sequence')?.remove();const d=document.createElement('div');d.className='versus-sequence';const intro=HERO_INTROS[hero]||['FIGHTER READY','Enter the arena.'];d.innerHTML=`<div class="vs-top">VILLAIN GAUNTLET</div><div class="vs-row"><div class="vs-side player"><small>CHALLENGER</small><strong>${hero}</strong><span>${intro[0]}</span></div><b class="vs-mark">VS</b><div class="vs-side enemy"><small>${fight.classList.contains('boss-mode')?'BOSS ENCOUNTER':'TARGET'}</small><strong>${enemy}</strong><span>${fight.classList.contains('boss-mode')?'FINAL THREAT':'STAND YOUR GROUND'}</span></div></div><div class="vs-tip">${intro[1]}</div>`;document.body.appendChild(d);requestAnimationFrame(()=>d.classList.add('show'));sfx('primary');setTimeout(()=>d.classList.add('leave'),1450);setTimeout(()=>d.remove(),1900)}
function hitFeedback(){const p=$('#pF'),e=$('#eF');[p,e].forEach(node=>{if(!node||node.dataset.polishHit)return;node.dataset.polishHit='1';new MutationObserver(()=>{if(node.classList.contains('hurt')){node.classList.remove('impact-pop');void node.offsetWidth;node.classList.add('impact-pop');document.body.classList.add('micro-hitstop');setTimeout(()=>document.body.classList.remove('micro-hitstop'),45);setTimeout(()=>node.classList.remove('impact-pop'),150)}}).observe(node,{attributes:true,attributeFilter:['class']})})}
function bossHud(){const fight=$('#fight');let hud=$('#bossPhaseHud');if(!fight?.classList.contains('active')||!fight.classList.contains('boss-mode')){hud?.remove();lastBossPhase=0;return}const enemy=cleanName($('#ename')?.textContent);if(!hud){hud=document.createElement('div');hud.id='bossPhaseHud';hud.className='boss-phase-hud';hud.innerHTML='<small>BOSS PROTOCOL</small><strong></strong><div class="boss-phase-track"><i></i><i></i><i></i></div><span></span>';fight.appendChild(hud)}hud.querySelector('strong').textContent=enemy;let hp=100;const bar=$('#ehp');if(bar){const w=parseFloat(bar.style.width);if(Number.isFinite(w))hp=w}const phase=hp<=24?3:hp<=52?2:1;hud.dataset.phase=phase;hud.querySelector('span').textContent=phase===1?'PHASE I • ANALYZE':phase===2?'PHASE II • AGGRESSIVE':'FINAL PROTOCOL';all('.boss-phase-track i',hud).forEach((x,i)=>x.classList.toggle('active',i<phase));if(phase>lastBossPhase&&lastBossPhase){hud.classList.add('phase-shift');sfx('reward');setTimeout(()=>hud.classList.remove('phase-shift'),700)}lastBossPhase=phase}
function profileDetails(){const profile=$('.profile');const title=$('#charTitle');if(!profile||!title)return;let box=$('#fighterDetailGrid');if(!box){box=document.createElement('div');box.id='fighterDetailGrid';box.className='fighter-detail-grid';profile.appendChild(box)}const name=cleanName(title.textContent);if(!name){box.innerHTML='';return}const map={
 'SPIDER-MAN':['S','ACROBAT','Mobility','Web control','Fast evasive pressure'], 'IRON MAN':['S','TECH','Range','Armor systems','Repulsor zoning'], 'WOLVERINE':['S','BERSERKER','Sustain','Regeneration','Relentless close range'], 'BLACK PANTHER':['A+','KINETIC','Precision','Energy storage','Counter-pressure'], 'CAPTAIN AMERICA':['A+','TACTICAL','Defense','Shield mastery','Reliable all-rounder'], 'MOON KNIGHT':['A+','MYSTIC','Burst','Moon Guard','High-risk pressure'], 'DAREDEVIL':['A','RADAR','Counter','Mobility','Technical fighter'], 'PUNISHER':['A','ARSENAL','Range','Explosives','Campaign unlock'], 'EL PRIMO':['A','BRAWLER','Power','Durability','Close-range bruiser'], 'ROOKIE':['B','BALANCED','Basics','Learning curve','Beginner friendly']};
 const d=map[name]||['—','FIGHTER','Combat','Unique kit','Multiverse combatant'];box.innerHTML=`<span><small>RANK</small><b>${d[0]}</b></span><span><small>CLASS</small><b>${d[1]}</b></span><span><small>STRENGTH</small><b>${d[2]}</b></span><span><small>SIGNATURE</small><b>${d[3]}</b></span><p>${d[4]}</p>`}
function koVictory(){const r=$('#results');if(!r||r.dataset.polishWatch)return;r.dataset.polishWatch='1';new MutationObserver(()=>{if(!r.classList.contains('active'))return;const win=r.classList.contains('victory');document.body.classList.add(win?'victory-cinematic':'defeat-cinematic');setTimeout(()=>document.body.classList.remove('victory-cinematic','defeat-cinematic'),1200);const title=$('#resultTitle');if(title){title.classList.remove('result-slam');void title.offsetWidth;title.classList.add('result-slam')}if(win)sfx('reward')}).observe(r,{attributes:true,attributeFilter:['class']})}
function gauntletCompletion(){const cards=$('#levelCards');if(!cards)return;let cleared=all('.campaign-node.cleared',cards).length,total=all('.campaign-node',cards).filter(x=>!x.classList.contains('assigned')).length;if(!total||cleared<total)return;if(document.querySelector('.gauntlet-complete'))return;const d=document.createElement('div');d.className='gauntlet-complete';d.innerHTML='<small>VILLAIN GAUNTLET</small><strong>GAUNTLET COMPLETE</strong><span>Every available threat has been defeated.</span><b>🏆 MULTIVERSE CONQUERED</b><button type="button">CONTINUE</button>';document.body.appendChild(d);d.querySelector('button').onclick=()=>d.remove();requestAnimationFrame(()=>d.classList.add('show'));sfx('reward')}
function quality(){all('.campaign-node').forEach(n=>{if(n.classList.contains('ready')&&!n.querySelector('.quality-pulse')){const i=document.createElement('i');i.className='quality-pulse';n.appendChild(i)}});all('.card,.skin-card').forEach(c=>{if(c.classList.contains('active'))c.setAttribute('aria-current','true');else c.removeAttribute('aria-current')});const sp=$('#special');if(sp&&!sp.dataset.readyWatch){sp.dataset.readyWatch='1';new MutationObserver(()=>{if(!sp.disabled){sp.classList.remove('ability-ready-flash');void sp.offsetWidth;sp.classList.add('ability-ready-flash')}}).observe(sp,{attributes:true,attributeFilter:['disabled']})}}
function soundPolish(){const fight=$('#fight');if(!fight||fight.dataset.soundPolish)return;fight.dataset.soundPolish='1';document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('#punch,#kick,#special,.hero-actions button');if(!b)return;if(b.id==='special')sfx('primary');else window.MultiverseArenaUI?.click?.('tap')},{passive:true})}
function loop(){renameGauntlet();arenaAtmosphere();hitFeedback();bossHud();profileDetails();quality();if($('#fight')?.classList.contains('active'))versusIntro();if($('#levels')?.classList.contains('active'))gauntletCompletion();requestAnimationFrame(loop)}
function brand(){document.title='Multiverse Arena v0.9.5.7.2 — Combat Polish & Immersion';all('.brand .tag').forEach(x=>x.textContent='v0.9.5.7.2');const u=$('#updates');if(u)u.textContent='📋 UPDATE LOG • v0.9.5.7.2';const l=$('.latest-stat');if(l){$('b',l).textContent='v0.9.5.7.2';$('span',l).textContent='Villain Gauntlet • Combat Polish • Immersion'}const h=$('.build-health b');if(h)h.textContent='IMMERSION CORE • v0.9.5.7.2'}
function updateLog(){const box=$('#updatesScreen .changelog');if(!box||box.querySelector('.polish-9572'))return;[['🥊','Combat Impact Upgrade','Stronger hit reactions, micro hit-stop and cleaner impact feedback make heavy attacks feel more physical.'],['🎬','Character Fight Intros','Every playable fighter now enters fights through a polished VS presentation with character-specific flavor.'],['🏆','KO & Victory Presentation','Results now land with cinematic victory/defeat feedback and stronger reward presentation.'],['👹','Boss Protocol HUD','Boss fights now communicate escalating phases directly in the fight HUD.'],['🌃','Arena Atmosphere','Haze, ambient lights and subtle motion make arenas feel less static without obscuring combat.'],['📁','Fighter Profile Details','Collection profiles now expose rank, class, strengths, signature systems and combat identity.'],['⚔️','Villain Gauntlet','Campaign has been renamed Villain Gauntlet and receives a stronger completion presentation.'],['🔊','Sound & Quality Polish','Combat control feedback, ability-ready flashes, ready-state pulses and accessibility details finish the pass.']].reverse().forEach(([i,t,p])=>{const d=document.createElement('div');d.className='log-item polish-9572';d.innerHTML=`<div class="log-icon">${i}</div><div><b>${t}</b><p>${p}</p></div>`;box.prepend(d)});const tag=$('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.5.7.2 • COMBAT POLISH & IMMERSION';const title=$('#updatesScreen .panel>h2');if(title)title.textContent='THE GAUNTLET FEELS ALIVE.'}
function init(){brand();renameGauntlet();updateLog();koVictory();soundPolish();document.documentElement.dataset.polishBuild=BUILD;requestAnimationFrame(loop);window.MultiverseArenaPolish={version:BUILD};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);addEventListener('fightarena-ready',()=>setTimeout(()=>{brand();renameGauntlet();updateLog()},100));
})();