/* Multiverse Arena v0.9.5.7.1 — Premium UI interaction + generated SFX */
(()=>{
'use strict';
const BUILD='0.9.5.7.1',KEY='multiverseArenaUiSfx';
let sfx=true,ctx=null,ready=false;
try{sfx=localStorage.getItem(KEY)!=='off'}catch{}
function audio(){if(!sfx)return null;try{if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}catch{return null}}
function tone(freq=420,dur=.045,gain=.025,type='sine',delay=0){const a=audio();if(!a)return;const t=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+dur+.02)}
function clickSound(kind='tap'){if(!sfx)return;if(kind==='primary'){tone(360,.055,.025,'triangle');tone(620,.065,.018,'sine',.018)}else if(kind==='back'){tone(330,.045,.018,'triangle');tone(250,.045,.012,'triangle',.018)}else if(kind==='reward'){tone(520,.075,.023,'sine');tone(720,.09,.022,'sine',.065);tone(920,.12,.018,'sine',.14)}else if(kind==='error'){tone(180,.08,.025,'sawtooth')}else tone(470,.035,.016,'triangle')}
function setSfx(on){sfx=!!on;try{localStorage.setItem(KEY,sfx?'on':'off')}catch{}renderToggle();if(sfx)clickSound('primary')}
function ripple(btn,e){if(!btn||btn.disabled)return;const r=btn.getBoundingClientRect(),x=e?.clientX?r.left?e.clientX-r.left:r.width/2:r.width/2,y=e?.clientY?r.top?e.clientY-r.top:r.height/2:r.height/2,n=document.createElement('i');n.className='ui-ripple';n.style.left=x+'px';n.style.top=y+'px';btn.appendChild(n);setTimeout(()=>n.remove(),540);btn.classList.add('ui-pressed');setTimeout(()=>btn.classList.remove('ui-pressed'),120)}
function kind(btn){if(btn.classList.contains('primary')||btn.id==='play'||btn.id==='continue'||btn.id==='start'||btn.id==='trainingStart')return'primary';if(btn.classList.contains('back')||btn.id==='menu'||btn.id==='pauseMenu')return'back';return'tap'}
function globalButtons(){document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('button');if(!b||b.disabled)return;ripple(b,e);clickSound(kind(b))},{passive:true});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target?.matches?.('button'))clickSound(kind(e.target))})}
function addSfxSetting(){const grid=document.querySelector('#settingsScreen .settings-grid');if(!grid||document.getElementById('uiSfxToggle'))return;const row=document.createElement('div');row.className='setting-row ui-sfx-row';row.innerHTML='<div><b>UI SOUND EFFECTS</b><span>Premium menu clicks, confirms and reward feedback generated directly in the browser.</span><span id="uiSfxStatus" class="ui-sound-badge"></span></div><button id="uiSfxToggle" type="button">ON</button>';grid.appendChild(row);row.querySelector('button').onclick=e=>{e.stopPropagation();setSfx(!sfx)};renderToggle()}
function renderToggle(){const b=document.getElementById('uiSfxToggle'),s=document.getElementById('uiSfxStatus');if(b){b.textContent=sfx?'ON':'OFF';b.classList.toggle('ui-toggle-on',sfx)}if(s){s.textContent=sfx?'AUDIO FEEDBACK ACTIVE':'AUDIO FEEDBACK OFF';s.classList.toggle('off',!sfx)}}
function brand(){document.title='Multiverse Arena v0.9.5.7.1 — UI Revamp';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.5.7.1');const u=document.getElementById('updates');if(u)u.textContent='📋 UPDATE LOG • v0.9.5.7.1';const latest=document.querySelector('.latest-stat');if(latest){const b=latest.querySelector('b'),s=latest.querySelector('span');if(b)b.textContent='v0.9.5.7.1';if(s)s.textContent='Premium UI Revamp • UI Sounds • Polish'}const h=document.querySelector('.build-health b');if(h)h.textContent='UI REVAMP • v0.9.5.7.1';const chooser=document.querySelector('#deviceChooser .eyebrow');if(chooser)chooser.textContent='MULTIVERSE ARENA v0.9.5.7.1'}
function updateLog(){const box=document.querySelector('#updatesScreen .changelog');if(!box||box.querySelector('.ui-revamp-log'))return;const items=[['✨','Premium UI Revamp','Every major screen has cleaner glass panels, stronger hierarchy, modern spacing, polished cards and more consistent interaction states.'],['🔊','Generated UI Sounds','Buttons now have lightweight generated click and confirm sounds with no external audio files. Toggle them any time in Settings.'],['🎮','Combat HUD Polish','Health, Special, ability controls and fight overlays have been cleaned up without touching combat balance or boss logic.'],['📱','Mobile-first Finish','iPhone and iPad layouts keep touch controls while receiving the same cleaner spacing, buttons and readable hierarchy.']];items.reverse().forEach(([icon,title,text])=>{const d=document.createElement('div');d.className='log-item ui-revamp-log';d.innerHTML=`<div class="log-icon">${icon}</div><div><b>${title}</b><p>${text}</p></div>`;box.prepend(d)});const tag=document.querySelector('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.5.7.1 • PREMIUM UI REVAMP';const title=document.querySelector('#updatesScreen .panel>h2');if(title)title.textContent='A CLEANER MULTIVERSE.'}
function rewardWatch(){const result=document.getElementById('results');if(!result)return;new MutationObserver(()=>{if(result.classList.contains('active')&&result.classList.contains('victory'))setTimeout(()=>clickSound('reward'),220)}).observe(result,{attributes:true,attributeFilter:['class']})}
function screenWatch(){const app=document.querySelector('.app');if(!app)return;new MutationObserver(list=>{for(const m of list){if(m.type==='attributes'&&m.target.classList?.contains('screen')&&m.target.classList.contains('active'))m.target.animate?.([{opacity:.65,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:220,easing:'cubic-bezier(.2,.8,.2,1)'})}}).observe(app,{subtree:true,attributes:true,attributeFilter:['class']})}
function init(){if(ready)return;ready=true;brand();addSfxSetting();updateLog();globalButtons();rewardWatch();screenWatch();document.documentElement.dataset.uiBuild=BUILD;window.MultiverseArenaUI={version:BUILD,get sfx(){return sfx},setSfx,click:clickSound};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
addEventListener('fightarena-ready',()=>setTimeout(()=>{brand();addSfxSetting();updateLog()},80));
})();
