/* Multiverse Arena v0.9.7.4 — Hulkbuster Premium Variant */
(()=>{
'use strict';
const BUILD='0.9.7.4',ASSET='0974';
const $=(s,r=document)=>r.querySelector(s);
function style(){if($('#update0974Style'))return;const l=document.createElement('link');l.id='update0974Style';l.rel='stylesheet';l.href=`update-v0974.css?v=${ASSET}`;document.head.appendChild(l)}
function brand(){document.title='Multiverse Arena v0.9.7.4 — Hulkbuster';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.4');const u=$('#updates');if(u)u.textContent='UPDATE LOG  •  v0.9.7.4';const latest=$('.latest-stat');if(latest){const b=$('b',latest),s=$('span',latest);if(b)b.textContent='v0.9.7.4';if(s)s.textContent='Hulkbuster • Mythic Ability Variant • Veronica Crashdown'}const h=$('.build-health b');if(h)h.textContent='v0.9.7.4 • HULKBUSTER • STABLE';const chooser=$('#deviceChooser .eyebrow');if(chooser)chooser.textContent='MULTIVERSE ARENA • v0.9.7.4';document.documentElement.dataset.multiverseRelease=BUILD;if(window.MultiverseArenaRuntime){window.MultiverseArenaRuntime.version=BUILD;window.MultiverseArenaRuntime.asset=ASSET}}
function decorateHulkbuster(){document.querySelectorAll('.skin-card').forEach(card=>{if(card.querySelector('h3')?.textContent?.trim()==='HULKBUSTER'){card.classList.add('hulkbuster-premium-card');const desc=$('.skin-card-desc',card);if(desc)desc.textContent='MYTHIC Ability Variant • 175 HP • 98 Power • Heavy Armor';const small=[...card.querySelectorAll('small')].at(-1);if(small&&!/EQUIPPED|OWNED/.test(small.textContent))small.textContent='💎 250'}})}
function cleanUpdateLog(){const box=$('#updatesScreen .changelog');if(!box)return;const releases=[['🤖','v0.9.7.4 — Hulkbuster','Iron Man receives a colossal Mythic Ability Variant for 250 Diamonds with a fully rebuilt oversized red-and-gold heavy armor model.'],['💥','v0.9.7.4 — Heavy Assault Kit','Hulkbuster brings 175 HP, 98 Power, Heavy Armor damage reduction, Hulkbuster Slam, Micro Missile Swarm and Repulsor Barrage.'],['🛰️','v0.9.7.4 — Veronica Crashdown','A new premium special launches the Hulkbuster into a protected crashdown sequence for massive impact damage and knockback.'],['🗂️','v0.9.7.3 — Collection UX','Quick stats, one-tap equip and the true 24-hour 1,250 coin Daily Reward.'],['⚖️','v0.9.7.2 — Combat Balance','Targeted fighter buffs and Phase 3 fairness tuning.'],['🐾','v0.9.7.1 — Sabretooth + Stability','Sabretooth visual rework plus Result and version-flow stabilization.']];box.innerHTML=releases.map(([i,t,p])=>`<div class="log-item recent-release-v0974"><div class="log-icon">${i}</div><div><b>${t}</b><p>${p}</p></div></div>`).join('');const tag=$('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.7.4 • HULKBUSTER';const title=$('#updatesScreen .panel>h2');if(title)title.textContent='BUILT TO BREAK LIMITS.'}
function refresh(){style();brand();decorateHulkbuster();cleanUpdateLog()}
function init(){refresh();$('#gallery')?.addEventListener('click',()=>setTimeout(()=>{refresh()},90));$('#updates')?.addEventListener('click',()=>setTimeout(refresh,30));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(refresh,0)});addEventListener('pageshow',()=>setTimeout(refresh,0));window.MultiverseArenaUpdate0974={version:BUILD,refresh,brand}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();addEventListener('fightarena-ready',()=>setTimeout(refresh,450),{once:true});
})();
