/* Multiverse Arena v0.9.7.6.1 — Interface Repair & Code Cleanup */
(()=>{
'use strict';
const BUILD='0.9.7.6.1',ASSET='09761';
const $=(s,r=document)=>r.querySelector(s);
const ownsRelease=()=>{const v=window.MultiverseArenaRuntime?.version;return !v||v===BUILD};
let wired=false;
const MULTI_PHASE=new Set(['DOCTOR OCTOPUS','MAGNETO']);
function style(){if($('#update09761Style'))return;const l=document.createElement('link');l.id='update09761Style';l.rel='stylesheet';l.href=`update-v09761.css?v=${window.MultiverseArenaRuntime?.asset||ASSET}`;document.head.appendChild(l)}
function brand(){if(!ownsRelease())return;document.title='Multiverse Arena v0.9.7.6.1 — Interface Repair & Code Cleanup';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.6.1');const u=$('#updates');if(u)u.textContent='UPDATE LOG  •  v0.9.7.6.1';const latest=$('.latest-stat');if(latest){const b=$('b',latest),s=$('span',latest);if(b)b.textContent='v0.9.7.6.1';if(s)s.textContent='Boss HUD Repair • Collection Cleanup • Result Flow Fix'}const h=$('.build-health b');if(h)h.textContent='v0.9.7.6.1 • INTERFACE REPAIR • STABLE';const c=$('#deviceChooser .eyebrow');if(c)c.textContent='MULTIVERSE ARENA • v0.9.7.6.1';if(window.MultiverseArenaRuntime){window.MultiverseArenaRuntime.version=BUILD;window.MultiverseArenaRuntime.asset=ASSET}}
function fixBossProtocol(){const fight=$('#fight'),hud=$('#bossPhaseHud');if(!fight?.classList.contains('active')||!fight.classList.contains('boss-mode')||!hud)return;const hp=$('.hpgrid',fight),enemy=($('#ename')?.textContent||'').trim().toUpperCase();if(hp&&hud.previousElementSibling!==hp)hp.insertAdjacentElement('afterend',hud);hud.classList.add('boss-protocol-v09761');const multi=MULTI_PHASE.has(enemy);hud.dataset.staticBoss=multi?'0':'1';const label=$('span',hud);if(!multi&&label)label.textContent='BOSS ACTIVE • DIAMOND REWARD';if(!multi){const track=$('.boss-phase-track',hud);track?.querySelectorAll('i').forEach((x,i)=>x.classList.toggle('active',i===0))}$('#bossPhaseIndicatorV0976')?.remove()}
function scheduleBossFix(){[80,220,520,900,1500].forEach(ms=>setTimeout(fixBossProtocol,ms))}
function repairCollection(){const chars=$('#chars');if(!chars?.classList.contains('active'))return;const head=$('.sectionhead',chars),tabs=$('.collection-tabs',chars);if(head&&tabs&&tabs.previousElementSibling!==head)head.insertAdjacentElement('afterend',tabs);document.documentElement.classList.add('collection-repaired-v09761')}
function openCollectionClean(){setTimeout(()=>{repairCollection();try{window.scrollTo({top:0,behavior:'auto'})}catch{window.scrollTo(0,0)}},90)}
function cleanUpdateLog(){if(!ownsRelease())return;const box=$('#updatesScreen .changelog');if(!box)return;const items=[['🧹','v0.9.7.6.1 — Interface Repair','Cleaned overlapping interface systems instead of stacking more presentation layers.'],['👑','Boss Protocol Repair','Arena Champion, Kingpin, Doctor Octopus and Magneto now share one compact Boss Protocol row outside the arena. Multi-phase bosses retain phase progression without a second floating HUD.'],['🗂️','Collection Layout Repair','COLLECTION remains visible, Fighters/Skins no longer cover the page title, and fighter cards are displayed in cleaner rank categories with denser mobile cards.'],['🛡️','Captain America Shield Fix','Removed the legacy second shield renderer. Classic and Hydra Captain America now display one canonical shield, including correct Shield Throw visibility.'],['▶','Result Progression Fix','Legacy level-unlock copy can no longer leak ULTRON into the modern Gauntlet result flow.'],['📱','Mobile Cleanup','Rechecked narrow iPhone layouts, Collection overflow, Boss HUD spacing and purchase/navigation hierarchy.']];box.innerHTML=items.map(([i,t,p])=>`<div class="log-item recent-release-v09761"><div class="log-icon">${i}</div><div><b>${t}</b><p>${p}</p></div></div>`).join('');const tag=$('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.7.6.1 • INTERFACE REPAIR';const title=$('#updatesScreen .panel>h2');if(title)title.textContent='CLEANER SYSTEMS. CLEARER FIGHTS.'}
function wire(){if(wired)return;wired=true;['start','continue','rematch'].forEach(id=>$('#'+id)?.addEventListener('click',scheduleBossFix));$('#gallery')?.addEventListener('click',openCollectionClean);document.querySelectorAll('[data-collection-tab]').forEach(b=>b.addEventListener('click',()=>setTimeout(repairCollection,60)));$('#charCards')?.addEventListener('click',()=>setTimeout(repairCollection,70));$('#skinCards')?.addEventListener('click',()=>setTimeout(repairCollection,70));addEventListener('pageshow',()=>{setTimeout(()=>{repairCollection();fixBossProtocol();brand()},0)});document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(()=>{repairCollection();fixBossProtocol()},0)})}
function refresh(){style();brand();repairCollection();fixBossProtocol();cleanUpdateLog();wire()}
function init(){refresh();window.MultiverseArenaUpdate09761={version:BUILD,refresh,fixBossProtocol,repairCollection}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
addEventListener('fightarena-ready',()=>setTimeout(()=>{refresh();scheduleBossFix()},700),{once:true});
})();
