/* Multiverse Arena v0.9.7.7 — Hero Update + Bug Fixes */
(()=>{
'use strict';
const BUILD='0.9.7.7',ASSET='0977',SAVE_KEY='fightArenaV08',$=(s,r=document)=>r.querySelector(s);let wired=false;
function style(){if($('#update0977Style'))return;const l=document.createElement('link');l.id='update0977Style';l.rel='stylesheet';l.href=`update-v0977.css?v=${ASSET}`;document.head.appendChild(l)}
function readOwned(){let raw={};try{raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')||{}}catch{}return {Rookie:true,...(raw.owned||{})}}
function brand(){document.title='Multiverse Arena v0.9.7.7 — Hero Update + Bug Fixes';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.7');const u=$('#updates');if(u)u.textContent='UPDATE LOG  •  v0.9.7.7';const latest=$('.latest-stat');if(latest){const b=$('b',latest),s=$('span',latest);if(b)b.textContent='v0.9.7.7';if(s)s.textContent='Thor • Doctor Strange • Star-Lord • Mobile + Training Fixes'}const h=$('.build-health b');if(h)h.textContent='v0.9.7.7 • HERO UPDATE • STABLE';const hero=$('#home .hero-copy');if(hero){const tag=$('.tag',hero),title=$('h1',hero),p=$('p',hero);if(tag)tag.textContent='HERO UPDATE • THREE NEW FIGHTERS';if(title)title.innerHTML='GODS. MAGIC.<br>GALACTIC FIREPOWER.';if(p)p.textContent='Thor, Doctor Strange and Star-Lord join the roster with dedicated combat kits, premium silhouettes and unique animated Specials.'}}
function fighterName(card){return card?.dataset?.fighterName||$('h3',card)?.textContent?.trim()||''}
function repairFilters(){const bar=$('.collection-filter-v0976[data-filter-type="fighters"]'),cards=[...document.querySelectorAll('#charCards .rank-fighters-grid>.card')];if(!bar||!cards.length)return;const owned=readOwned(),active=$('[data-filter].active',bar)?.dataset.filter||'all';let total=0,ownedCount=0,visible=0;cards.forEach(card=>{const name=fighterName(card);if(!name||name==='The One Above All')return;total++;const has=!!owned[name];if(has)ownedCount++;card.dataset.ownedV0977=has?'1':'0';card.classList.toggle('collection-locked-v0977',!has);const show=active==='all'||(active==='owned'&&has)||(active==='locked'&&!has);card.classList.toggle('filter-hidden-v0976',!show);if(show)visible++});const count=$('.collection-filter-count-v0976',bar);if(count)count.textContent=`${visible}/${total} • OWNED ${ownedCount} • 🔒 ${Math.max(0,total-ownedCount)}`}
function trainingRepair(){const fill=$('#trainingSpecial'),reset=$('#trainingReset');if(fill&&!fill.dataset.v0977){fill.dataset.v0977='1';fill.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();window.FightArenaTrainingControls?.fill?.()},{capture:true})}if(reset&&!reset.dataset.v0977){reset.dataset.v0977='1';reset.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();window.FightArenaTrainingControls?.reset?.()},{capture:true})}}
function phaseRepair(){const tabs=$('#levelCards .gauntlet-phase-tabs-v0966');if(!tabs)return;tabs.classList.add('phase-tabs-v0977');const active=$('.gauntlet-phase-tab-v0966.active',tabs);if(innerWidth<=700&&active&&document.activeElement!==active)active.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}
function updateLog(){const box=$('#updatesScreen .changelog');if(!box)return;const rows=[['⚡','Thor','S Rank Asgardian powerhouse with Mjolnir Throw, Lightning Strike, Thunder Rush and God of Thunder.'],['🔮','Doctor Strange','S Rank control fighter with Eldritch Bolts, Portal Strike, Seraphim Shield and Mirror Dimension.'],['🚀','Star-Lord','A+ ranged mobility fighter with Element Blasters, Jet Boot Dash, Gravity Mine and Legendary Outlaw.'],['📱','Mobile Phase selector','Phone phase tabs scroll horizontally instead of overlapping; tablet layout stays wide.'],['🎯','Training repair','FILL SPECIAL and RESET reconnect directly to the canonical Training API.'],['🔒','Collection ownership filters','ALL / OWNED / LOCKED now read actual saved ownership and locked fighters get a clear lock badge.']];box.innerHTML=rows.map(([i,t,p])=>`<div class="log-item"><div class="log-icon">${i}</div><div><b>${t}</b><p>${p}</p></div></div>`).join('')}
function audit(){style();brand();repairFilters();trainingRepair();phaseRepair()}
function wire(){if(wired)return;wired=true;$('#gallery')?.addEventListener('click',()=>setTimeout(repairFilters,120));$('#charCards')?.addEventListener('click',()=>setTimeout(repairFilters,100));$('#play')?.addEventListener('click',()=>setTimeout(phaseRepair,160));$('#levelCards')?.addEventListener('click',()=>setTimeout(phaseRepair,70));$('#updates')?.addEventListener('click',()=>setTimeout(updateLog,40));addEventListener('resize',()=>setTimeout(phaseRepair,80));addEventListener('storage',e=>{if(e.key===SAVE_KEY)setTimeout(repairFilters,50)});addEventListener('pageshow',()=>setTimeout(audit,0))}
function init(){audit();updateLog();wire();window.MultiverseArenaUpdate0977={version:BUILD,audit,repairFilters,trainingRepair,phaseRepair}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();addEventListener('fightarena-ready',()=>setTimeout(init,500),{once:true});
})();
