/* Multiverse Arena v0.9.7.5 — Collection Shop + Purchase Confirmation */
(()=>{
'use strict';
const BUILD='0.9.7.5',ASSET='0975';
const $=(s,r=document)=>r.querySelector(s);
const ownsRelease=()=>{const v=window.MultiverseArenaRuntime?.version;return !v||v===BUILD};
let wired=false,purchaseBypass=false,pending=null,lastFocus=null;
function style(){if($('#update0975Style'))return;const l=document.createElement('link');l.id='update0975Style';l.rel='stylesheet';l.href=`update-v0975.css?v=${ASSET}`;document.head.appendChild(l)}
function numberFrom(text=''){const n=Number(String(text).replace(/[^0-9]/g,''));return Number.isFinite(n)?n:0}
function balance(currency){return numberFrom($(currency==='coins'?'#coins':'#gems')?.textContent||'0')}
function currencyIcon(currency){return currency==='coins'?'🪙':'💎'}
function brand(){
 if(!ownsRelease())return;
 document.title='Multiverse Arena v0.9.7.5 — Collection Shop';
 document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.5');
 const u=$('#updates');if(u)u.textContent='UPDATE LOG  •  v0.9.7.5';
 const latest=$('.latest-stat');if(latest){const b=$('b',latest),s=$('span',latest);if(b)b.textContent='v0.9.7.5';if(s)s.textContent='Card Shop • Purchase Confirmation • Faster Skins'}
 const health=$('.build-health b');if(health)health.textContent='v0.9.7.5 • COLLECTION SHOP • STABLE';
 const chooser=$('#deviceChooser .eyebrow');if(chooser)chooser.textContent='MULTIVERSE ARENA • v0.9.7.5';
 const hero=$('#home .hero-copy');if(hero){const tag=$('.tag',hero),h=$('h1',hero),p=$('p',hero);if(tag)tag.textContent='COLLECTION • SHOP UPGRADE';if(h)h.innerHTML='BROWSE. CONFIRM.<br>BUILD YOUR ROSTER.';if(p)p.textContent='Buy fighters and skins directly from their cards. Every currency purchase now requires a clear confirmation before coins or Diamonds are spent.'}
 document.documentElement.dataset.multiverseRelease=BUILD;
 if(window.MultiverseArenaRuntime){window.MultiverseArenaRuntime.version=BUILD;window.MultiverseArenaRuntime.asset=ASSET}
}
function ensureToolbar(pane,type){if(!pane)return;let bar=$(`.shop-toolbar-v0975[data-shop-type="${type}"]`,pane);if(!bar){bar=document.createElement('div');bar.className='shop-toolbar-v0975';bar.dataset.shopType=type;bar.innerHTML=`<div><small>COLLECTION SHOP</small><b>${type==='fighters'?'FIGHTERS':'SKINS + ABILITY VARIANTS'}</b><span>Buy or equip directly from each card. Purchases always require confirmation.</span></div><div class="shop-balances-v0975"><span>🪙 <b data-shop-coins>0</b></span><span>💎 <b data-shop-gems>0</b></span></div>`;pane.insertBefore(bar,pane.firstChild)}syncBalances()}
function syncBalances(){document.querySelectorAll('[data-shop-coins]').forEach(x=>x.textContent=balance('coins').toLocaleString());document.querySelectorAll('[data-shop-gems]').forEach(x=>x.textContent=balance('gems').toLocaleString())}
function ensureModal(){let modal=$('#purchaseConfirmV0975');if(modal)return modal;modal=document.createElement('div');modal.id='purchaseConfirmV0975';modal.className='purchase-confirm-v0975 hidden';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','purchaseConfirmTitleV0975');modal.innerHTML=`<div class="purchase-confirm-card-v0975"><button class="purchase-close-v0975" id="purchaseCloseV0975" type="button" aria-label="Cancel purchase">×</button><div class="purchase-confirm-preview-v0975" id="purchasePreviewV0975"></div><small id="purchaseTypeV0975">PURCHASE CONFIRMATION</small><h2 id="purchaseConfirmTitleV0975">CONFIRM PURCHASE</h2><p id="purchaseCopyV0975"></p><div class="purchase-price-v0975"><div><small>PRICE</small><b id="purchasePriceV0975"></b></div><div><small>YOUR BALANCE</small><b id="purchaseBalanceV0975"></b></div></div><div class="purchase-warning-v0975" id="purchaseWarningV0975">Nothing is spent until you press CONFIRM.</div><div class="purchase-actions-v0975"><button id="purchaseCancelV0975" type="button">CANCEL</button><button id="purchaseConfirmBtnV0975" class="primary" type="button">CONFIRM</button></div></div>`;document.body.appendChild(modal);return modal}
function closeConfirm(){const modal=$('#purchaseConfirmV0975');if(modal)modal.classList.add('hidden');pending=null;document.documentElement.classList.remove('purchase-open-v0975');lastFocus?.focus?.();lastFocus=null}
function openConfirm(opts){const modal=ensureModal(),icon=currencyIcon(opts.currency),funds=balance(opts.currency),enough=funds>=opts.price;pending=opts;lastFocus=document.activeElement;$('#purchasePreviewV0975').innerHTML=opts.previewHTML||'';$('#purchaseTypeV0975').textContent=`${opts.type.toUpperCase()} PURCHASE`;$('#purchaseConfirmTitleV0975').textContent=`BUY ${opts.name.toUpperCase()}?`;$('#purchaseCopyV0975').textContent=opts.type==='skin'?'This skin will be added to your Collection and can be equipped immediately.':'This fighter will be permanently added to your Collection.';$('#purchasePriceV0975').textContent=`${opts.price.toLocaleString()} ${icon}`;$('#purchaseBalanceV0975').textContent=`${funds.toLocaleString()} ${icon}`;const warning=$('#purchaseWarningV0975'),confirm=$('#purchaseConfirmBtnV0975');warning.textContent=enough?'Nothing is spent until you press CONFIRM.':`You need ${(opts.price-funds).toLocaleString()} more ${opts.currency==='coins'?'coins':'Diamonds'} for this purchase.`;warning.classList.toggle('insufficient',!enough);confirm.disabled=!enough;confirm.textContent=enough?`CONFIRM • ${opts.price.toLocaleString()} ${icon}`:'NOT ENOUGH CURRENCY';modal.classList.remove('hidden');document.documentElement.classList.add('purchase-open-v0975');setTimeout(()=>$(enough?'#purchaseConfirmBtnV0975':'#purchaseCancelV0975')?.focus(),0)}
function runUnderlying(button){if(!button)return false;purchaseBypass=true;try{button.click()}finally{purchaseBypass=false}setTimeout(refreshShop,90);return true}
function directFighterAction(card,name,c,state){if(state==='buy'){openConfirm({type:'fighter',name,price:Number(c.price)||0,currency:'coins',previewHTML:$('.portrait',card)?.innerHTML||'',commit(){card.click();setTimeout(()=>runUnderlying($('#charAction')),0)}});return}if(state==='equip'){card.click();setTimeout(()=>runUnderlying($('#charAction')),0)}}
function decorateFighters(){const box=$('#charCards'),chars=window.FightArena?.chars||{};if(!box)return;box.querySelectorAll('.rank-fighters-grid>.card').forEach(card=>{const visibleName=$('h3',card)?.textContent?.trim()||'',baseName=card.dataset.fighterName||visibleName,entry=chars[baseName]?[baseName,chars[baseName]]:Object.entries(chars).find(([n])=>n.toUpperCase()===visibleName.toUpperCase());if(!entry)return;const [hero,c]=entry;card.dataset.fighterName=hero;const status=[...card.children].find(n=>n.tagName==='SMALL')?.textContent||'',selected=/SELECTED/.test(status),owned=/OWNED|SELECTED/.test(status),canBuy=!owned&&Number(c.price)>0;$('.fighter-quick-action-v0973',card)?.setAttribute('tabindex','-1');let a=$('.fighter-shop-action-v0975',card);if(!a){a=document.createElement('span');a.className='fighter-shop-action-v0975';a.setAttribute('role','button');a.tabIndex=0;card.appendChild(a)}const state=selected?'selected':owned?'equip':canBuy?'buy':'locked';a.dataset.shopState=state;a.textContent=selected?'✓ EQUIPPED':owned?'EQUIP':canBuy?`BUY • ${Number(c.price).toLocaleString()} 🪙`:'UNLOCK REQUIRED';a.setAttribute('aria-disabled',selected||state==='locked'?'true':'false');a.setAttribute('aria-label',canBuy?`Buy ${hero} for ${Number(c.price).toLocaleString()} coins`:owned?`Equip ${hero}`:`${hero} unavailable`);a.onclick=e=>{e.preventDefault();e.stopPropagation();if(state==='buy'||state==='equip')directFighterAction(card,hero,c,state)};a.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&(state==='buy'||state==='equip')){e.preventDefault();e.stopPropagation();directFighterAction(card,hero,c,state)}}})}
function directSkinAction(card,name,price,state){const act=()=>{card.click();setTimeout(()=>runUnderlying($('#skinAction')),0)};if(state==='buy'){openConfirm({type:'skin',name,price,currency:'gems',previewHTML:$('.portrait',card)?.innerHTML||'',commit:act});return}if(state==='equip')act()}
function decorateSkins(){const box=$('#skinCards');if(!box)return;box.querySelectorAll('.skin-card').forEach(card=>{const name=$('h3',card)?.textContent?.trim()||'Skin',status=[...card.children].find(n=>n.tagName==='SMALL')?.textContent?.trim()||'',equipped=/EQUIPPED/.test(status),owned=status==='OWNED',locked=/OWN HERO FIRST/.test(status),price=/^💎/.test(status)?numberFrom(status):0,state=equipped?'selected':owned?'equip':locked?'locked':price>0?'buy':'locked';let a=$('.skin-shop-action-v0975',card);if(!a){a=document.createElement('span');a.className='skin-shop-action-v0975';a.setAttribute('role','button');a.tabIndex=0;card.appendChild(a)}a.dataset.shopState=state;a.textContent=equipped?'✓ EQUIPPED':owned?'EQUIP':locked?'OWN HERO FIRST':price>0?`BUY • ${price.toLocaleString()} 💎`:'UNAVAILABLE';a.setAttribute('aria-disabled',equipped||locked||state==='locked'?'true':'false');a.setAttribute('aria-label',price>0?`Buy ${name} for ${price} Diamonds`:owned?`Equip ${name}`:`${name} unavailable`);a.onclick=e=>{e.preventDefault();e.stopPropagation();if(state==='buy'||state==='equip')directSkinAction(card,name,price,state)};a.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&(state==='buy'||state==='equip')){e.preventDefault();e.stopPropagation();directSkinAction(card,name,price,state)}}})}
function interceptLegacyPurchase(e){const b=e.target.closest?.('#charAction,#skinAction');if(!b||purchaseBypass||!/^BUY\s*•/i.test(b.textContent.trim()))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const isSkin=b.id==='skinAction',price=numberFrom(b.textContent),currency=isSkin?'gems':'coins',name=$(isSkin?'#skinTitle':'#charTitle')?.textContent?.trim()||(isSkin?'Skin':'Fighter'),previewHTML=$(isSkin?'#skinPreview':'#charCards .card.active .portrait')?.innerHTML||'';openConfirm({type:isSkin?'skin':'fighter',name,price,currency,previewHTML,commit:()=>runUnderlying(b)})}
function cleanUpdateLog(){if(!ownsRelease())return;const box=$('#updatesScreen .changelog');if(!box)return;const releases=[['🛒','v0.9.7.5 — Collection Shop','Fighters and skins now have clear BUY / EQUIP actions directly on their cards, with compact coin and Diamond balances at the top of each Collection tab.'],['✅','v0.9.7.5 — Purchase Confirmation','Every fighter or skin purchase now opens a dedicated confirmation card showing the item, exact cost and your current balance before any currency can be spent.'],['💎','v0.9.7.5 — Faster Skin Shopping','Every skin card now has its own BUY or EQUIP action. You no longer need to select a skin and scroll down to the old action button.'],['🦾','v0.9.7.4.1 — Hulkbuster + Rematch','Heavy-mech Hulkbuster rework and restored Results REMATCH flow remain intact.'],['🎁','v0.9.7.3 — Collection + Daily','Quick fighter stats and the true 24-hour 1,250 coin Daily Reward remain active.'],['⚖️','v0.9.7.2 — Combat Balance','Targeted fighter buffs and Phase 3 fairness tuning remain active.']];box.innerHTML=releases.map(([i,t,p])=>`<div class="log-item recent-release-v0975"><div class="log-icon">${i}</div><div><b>${t}</b><p>${p}</p></div></div>`).join('');const tag=$('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.7.5 • COLLECTION SHOP';const title=$('#updatesScreen .panel>h2');if(title)title.textContent='CLEARER CARDS. SAFER PURCHASES.'}
function refreshShop(){style();brand();$('#chars')?.classList.add('shop-v0975');ensureToolbar($('#fightersPane'),'fighters');ensureToolbar($('#skinsPane'),'skins');decorateFighters();decorateSkins();syncBalances();cleanUpdateLog();ensureModal()}
function wire(){if(wired)return;wired=true;document.addEventListener('click',interceptLegacyPurchase,true);$('#gallery')?.addEventListener('click',()=>setTimeout(refreshShop,120));document.querySelectorAll('[data-collection-tab]').forEach(b=>b.addEventListener('click',()=>setTimeout(refreshShop,80)));$('#charCards')?.addEventListener('click',()=>setTimeout(decorateFighters,45));$('#skinCards')?.addEventListener('click',()=>setTimeout(decorateSkins,45));$('#charAction')?.addEventListener('click',()=>setTimeout(refreshShop,100));$('#skinAction')?.addEventListener('click',()=>setTimeout(refreshShop,100));$('#updates')?.addEventListener('click',()=>setTimeout(()=>{brand();cleanUpdateLog()},30));$('#purchaseCancelV0975')?.addEventListener('click',closeConfirm);$('#purchaseCloseV0975')?.addEventListener('click',closeConfirm);$('#purchaseConfirmBtnV0975')?.addEventListener('click',()=>{const p=pending;if(!p)return;closeConfirm();p.commit?.()});$('#purchaseConfirmV0975')?.addEventListener('click',e=>{if(e.target.id==='purchaseConfirmV0975')closeConfirm()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pending){e.preventDefault();closeConfirm()}});addEventListener('pageshow',()=>setTimeout(refreshShop,0));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(refreshShop,0)})}
function refresh(){refreshShop();wire()}
function init(){ensureModal();refresh();window.MultiverseArenaUpdate0975={version:BUILD,refresh,decorateFighters,decorateSkins,openConfirm,closeConfirm}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
addEventListener('fightarena-ready',()=>setTimeout(refresh,520),{once:true});
})();
