/* Multiverse Arena v0.9.7.3 — Collection UX + True Daily Reward */
(()=>{
'use strict';
const BUILD='0.9.7.3',ASSET='0973';
const $=(s,r=document)=>r.querySelector(s);
const ownsRelease=()=>!window.MultiverseArenaRuntime||window.MultiverseArenaRuntime.version===BUILD;
let wired=false,dailyTimer=0;
function style(){if($('#update0973Style'))return;const l=document.createElement('link');l.id='update0973Style';l.rel='stylesheet';l.href=`update-v0973.css?v=${ASSET}`;document.head.appendChild(l)}
function brand(){if(!ownsRelease())return;document.title='Multiverse Arena v0.9.7.3 — Collection UX + Daily Reward';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.3');const updates=$('#updates');if(updates)updates.textContent='UPDATE LOG  •  v0.9.7.3';const latest=$('.latest-stat');if(latest){const b=$('b',latest),s=$('span',latest);if(b)b.textContent='v0.9.7.3';if(s)s.textContent='Quick Fighter Stats • One-Tap Equip • 24H Daily Reward'}const health=$('.build-health b');if(health)health.textContent='v0.9.7.3 • COLLECTION + DAILY REWARD • STABLE';const chooser=$('#deviceChooser .eyebrow');if(chooser)chooser.textContent='MULTIVERSE ARENA • v0.9.7.3';const hero=$('#home .hero-copy');if(hero){const tag=$('.tag',hero),h=$('h1',hero),p=$('p',hero);if(tag)tag.textContent='COLLECTION • QUALITY OF LIFE';if(h)h.innerHTML='YOUR ROSTER.<br>ONE TAP AWAY.';if(p)p.textContent='Compare fighter stats instantly, equip directly from each card and claim a boosted Daily Reward only once every true 24 hours.'}document.documentElement.dataset.multiverseRelease='0.9.7.3';if(window.MultiverseArenaRuntime){window.MultiverseArenaRuntime.version=BUILD;window.MultiverseArenaRuntime.asset=ASSET}}
function fighterByCard(card){const title=$('h3',card)?.textContent?.trim()?.toUpperCase();if(!title)return null;return Object.entries(window.FightArena?.chars||{}).find(([name])=>name.toUpperCase()===title)||null}
function decorateCards(){const box=$('#charCards');if(!box)return;box.querySelectorAll('.rank-fighters-grid>.card').forEach(card=>{const entry=fighterByCard(card);if(!entry)return;const [name,c]=entry;card.classList.add('fighter-card-v0973');card.dataset.fighterName=name;let stats=$('.fighter-quick-stats-v0973',card);if(!stats){stats=document.createElement('div');stats.className='fighter-quick-stats-v0973';stats.innerHTML=`<span><small>HP</small><b>${c.hp}</b></span><span><small>POWER</small><b>${c.power}</b></span><span><small>SPEED</small><b>${c.speed}</b></span>`;const role=$('.fighter-role',card);(role||$('h3',card))?.insertAdjacentElement('afterend',stats)}const status=[...card.children].find(n=>n.tagName==='SMALL'&&!n.closest('.fighter-quick-stats-v0973'))?.textContent||'';let action=$('.fighter-quick-action-v0973',card);if(!action){action=document.createElement('span');action.className='fighter-quick-action-v0973';action.setAttribute('role','button');action.tabIndex=0;card.appendChild(action)}const selected=/SELECTED/.test(status),owned=/OWNED|SELECTED/.test(status),canBuy=!owned&&Number(c.price)>0;action.className='fighter-quick-action-v0973 '+(selected?'equipped':canBuy?'buy':'equip');action.dataset.quickEquip='1';action.textContent=selected?'✓ EQUIPPED':owned?'EQUIP':canBuy?`BUY • ${Number(c.price).toLocaleString()} 🪙`:'UNLOCK REQUIRED';action.setAttribute('aria-disabled',selected||(!owned&&!canBuy)?'true':'false')})}
function quickEquip(card){const action=$('.fighter-quick-action-v0973',card);if(!card||action?.getAttribute('aria-disabled')==='true')return;card.click();setTimeout(()=>{$('#charAction')?.click();setTimeout(()=>{decorateCards();brand()},30)},0)}
function updateDaily(){const btn=$('#daily'),api=window.FightArenaDailyControls;if(!btn||!api?.snapshot)return;const s=api.snapshot();btn.classList.add('daily-v0973');btn.classList.toggle('daily-ready',!!s.ready);btn.classList.toggle('daily-cooldown',!s.ready);btn.disabled=!s.ready;btn.innerHTML=s.ready?`<span>🎁 DAILY REWARD</span><small>CLAIM +${Number(s.reward).toLocaleString()} 🪙</small>`:`<span>🎁 DAILY REWARD</span><small>NEXT IN ${s.timeText}</small>`;btn.setAttribute('aria-label',s.ready?`Claim daily reward: ${s.reward} coins`:`Daily reward available in ${s.timeText}`)}
function tickDaily(){clearTimeout(dailyTimer);updateDaily();dailyTimer=setTimeout(tickDaily,document.hidden?5000:1000)}
function cleanUpdateLog(){if(!ownsRelease())return;const box=$('#updatesScreen .changelog');if(!box)return;const releases=[['🗂️','v0.9.7.3 — Collection Quick View','Every fighter card now shows HP, Power and Speed directly, so comparing your roster no longer requires scrolling into the detail panel.'],['⚡','v0.9.7.3 — One-Tap Equip','Owned fighters can be equipped straight from their Collection card. Locked coin fighters can also be bought and selected from the same place.'],['🎁','v0.9.7.3 — Boosted Daily Reward','Daily Reward increases from 250 to 1,250 coins and now uses a real 24-hour timestamp instead of resetting by calendar day.'],['⏱️','v0.9.7.3 — Live Daily Countdown','The home-screen Daily Reward button shows HH:MM:SS until the exact next claim and automatically becomes claimable when the timer reaches zero.'],['⚖️','v0.9.7.2 — Combat Balance','Rookie, Captain America and Daredevil were buffed while Juggernaut, Deadpool and Magneto received fairness tuning.'],['🐾','v0.9.7.1 — Sabretooth + Stability','Sabretooth received his feral visual rework alongside Result-flow and release-number stabilization.']];box.dataset.cleaned0973='1';delete box.dataset.cleaned0972;delete box.dataset.cleaned0971;delete box.dataset.cleaned097;box.innerHTML=releases.map(([icon,title,text])=>`<div class="log-item recent-release-v0973"><div class="log-icon">${icon}</div><div><b>${title}</b><p>${text}</p></div></div>`).join('');const tag=$('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.7.3 • COLLECTION + DAILY REWARD';const title=$('#updatesScreen .panel>h2');if(title)title.textContent='LESS SCROLLING. MORE PLAYING.'}
function wire(){if(wired)return;wired=true;$('#gallery')?.addEventListener('click',()=>setTimeout(()=>{decorateCards();brand()},80));$('#charCards')?.addEventListener('click',e=>{const action=e.target.closest?.('.fighter-quick-action-v0973');if(action){e.preventDefault();e.stopPropagation();quickEquip(action.closest('.card'));return}setTimeout(decorateCards,20)},true);$('#charCards')?.addEventListener('keydown',e=>{const action=e.target.closest?.('.fighter-quick-action-v0973');if(action&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.stopPropagation();quickEquip(action.closest('.card'))}},true);$('#charAction')?.addEventListener('click',()=>setTimeout(decorateCards,30));$('#daily')?.addEventListener('click',()=>setTimeout(updateDaily,20));$('#updates')?.addEventListener('click',()=>setTimeout(()=>{brand();cleanUpdateLog()},30));addEventListener('fightarena-daily-updated',updateDaily);addEventListener('pageshow',()=>setTimeout(()=>{brand();decorateCards();cleanUpdateLog();updateDaily()},0));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(()=>{brand();decorateCards();updateDaily()},0)})}
function refresh(){style();brand();decorateCards();cleanUpdateLog();updateDaily();wire();tickDaily()}
function init(){refresh();window.MultiverseArenaUpdate0973={version:BUILD,refresh,brand,decorateCards,updateDaily,cleanUpdateLog}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();addEventListener('fightarena-ready',()=>setTimeout(refresh,380),{once:true});
})();
