/* Multiverse Arena v0.9.7.7.2 — Owner Board Rework */
(()=>{
'use strict';
const BUILD='0.9.7.7.2',ASSET='09772',SAVE_KEY='fightArenaV08',CODE='OWNERBOARD',$=(s,r=document)=>r.querySelector(s);
const fighters=['Rookie','El Primo','Spider-Man','Captain America','Iron Man','Daredevil','Moon Knight','Black Panther','Wolverine','Punisher','Thor','Doctor Strange','Star-Lord'];
const skins=['rookie-default','rookie-neo','primo-default','primo-gold','spider-default','spider-symbiote','cap-default','cap-hydra','iron-default','iron-nano','iron-hulkbuster','dd-default','mk-default','bp-default','bp-kinetic','wolverine-default','punisher-default','thor-default','strange-default','starlord-default'];
const campaign=['Nightfang','Voltage','Razor','Titan','Arena Champion','Crossbones','Bullseye','Punisher','Taskmaster','Kingpin','Rhino','Electro','Mysterio','Green Goblin','Doctor Octopus','Sabretooth','Mystique','Juggernaut','Deadpool','Magneto'];
function read(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')||{}}catch{return {}}}
function write(s){localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function unlocked(){return !!read().ownerBoardUnlocked}
function reloadWith(msg){sessionStorage.setItem('ownerBoardFlash',msg||'OWNER UPDATE APPLIED');location.reload()}
function mutate(label,fn){if(!confirm(label+'\n\nApply this Owner action?'))return;const s=read();fn(s);s.ownerBoardUnlocked=true;write(s);reloadWith(label)}
function injectStyle(){if($('#ownerBoardCss'))return;const l=document.createElement('link');l.id='ownerBoardCss';l.rel='stylesheet';l.href=`update-v09772.css?v=${ASSET}`;document.head.appendChild(l)}
function updateLog(){const box=$('#updatesScreen .changelog');if(!box)return;const rows=[['👑','Owner Board Rework','Redeem OWNERBOARD once, then reopen the Owner Command Center anytime from Settings or the floating Owner dock.'],['↕','Minimize & Restore','Collapse the Owner Board into a compact dock and restore it instantly without re-entering the code.'],['🧪','Developer Tools','Fight Launcher, combat flags, AI overrides, boss presets, save slots, campaign editor, performance HUD and bug snapshots are available to the owner.'],['🧹','Repo Cleanup','Production load auditing now checks the single-bootstrap architecture, missing runtime files and duplicate production loads.'],['🛡️','Safer Saves','Owner save restore rejects invalid save structures before writing them to local storage.'],['✨','UI Polish','Smoother board transitions, better scrolling and mobile-friendly owner controls improve iPad and phone use.']];box.innerHTML=rows.map(([i,t,p])=>`<div class="log-item owner-log-entry"><div class="log-icon">${i}</div><div><b>${t}</b><p>${p}</p></div></div>`).join('');const tag=$('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.7.7.2 • OWNER BOARD REWORK';const title=$('#updatesScreen .panel>h2');if(title)title.textContent='OWNER TOOLS ARE LIVE.'}
function brand(){document.title='Multiverse Arena v0.9.7.7.2 — Owner Board Rework';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.7.2');const u=$('#updates');if(u)u.textContent='UPDATE LOG  •  v0.9.7.7.2';const latest=$('.latest-stat');if(latest){const b=$('b',latest),s=$('span',latest);if(b)b.textContent='v0.9.7.7.2';if(s)s.textContent='Owner Board Rework • Dev Tools • Repo Cleanup'}const h=$('.build-health b');if(h)h.textContent='v0.9.7.7.2 • OWNER TOOLS • STABLE';const c=$('#deviceChooser .eyebrow');if(c)c.textContent='MULTIVERSE ARENA • v0.9.7.7.2';updateLog()}
function ensureDock(){if(!unlocked())return $('#ownerBoardDock')?.remove();if($('#ownerBoardDock'))return;const b=document.createElement('button');b.id='ownerBoardDock';b.type='button';b.className='owner-board-dock';b.innerHTML='<span>👑</span><b>OWNER</b><small>v0.9.7.7.2</small>';b.onclick=openBoard;document.body.appendChild(b)}
function showDock(show=true){const b=$('#ownerBoardDock');if(b)b.classList.toggle('owner-dock-hidden',!show)}
function redeemOwner(e){const input=$('#redeemInput');if(!input||input.value.trim().toUpperCase()!==CODE)return false;if(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.()}const s=read();s.ownerBoardUnlocked=true;s.redeemedOwnerBoard=true;write(s);injectStyle();ensureSettingsButton();ensureDock();const status=$('#redeemStatus');if(status){status.textContent='👑 OWNER ACCESS GRANTED — OPENING BOARD';status.className='redeem-status god'}input.value='';setTimeout(()=>openBoard(),60);return true}
function wireRedeem(){if(document.documentElement.dataset.ownerBoardDelegated)return;document.documentElement.dataset.ownerBoardDelegated='1';document.addEventListener('click',e=>{if(e.target?.closest?.('#redeemBtn'))redeemOwner(e);if(e.target?.closest?.('#updates'))setTimeout(()=>{brand();updateLog()},60)},true);document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.matches?.('#redeemInput'))redeemOwner(e)},true)}
function ensureSettingsButton(){if(!unlocked())return;const grid=$('#settingsScreen .settings-grid');if(!grid||$('#ownerBoardLaunch'))return;const row=document.createElement('div');row.className='setting-row owner-setting-row';row.innerHTML='<div><b>👑 OWNER BOARD • v0.9.7.7.2</b><span>Economy, Collection, Campaign, combat testing and save management.</span></div><button id="ownerBoardLaunch">OPEN</button>';grid.appendChild(row);$('#ownerBoardLaunch').onclick=openBoard}
function boardMarkup(){const s=read();return `<div id="ownerBoardOverlay" class="owner-board-overlay"><div class="owner-board-shell"><div class="owner-board-head"><div><small>👑 OWNER • v0.9.7.7.2 • LOCAL ADMIN</small><h2>OWNER COMMAND CENTER</h2><p>Economy, Collection, Campaign, fight testing, dev presets and save tools. Owner changes stay local to this device.</p></div><div class="owner-head-actions"><button id="ownerBoardMin" type="button" aria-label="Minimize Owner Board">—</button><button id="ownerBoardClose" type="button" aria-label="Close Owner Board">✕</button></div></div><div class="owner-summary"><span>BUILD <b>7.7.2</b></span><span>LV <b>${Number(s.lv)||1}</b></span><span>🪙 <b>${Number(s.coins)||0}</b></span><span>💎 <b>${Number(s.gems)||0}</b></span></div><div class="owner-grid">
<section><small>ECONOMY • 7.7.2</small><h3>CURRENCY</h3><div class="owner-input-row"><input id="ownerCoinsInput" type="number" min="0" value="${Number(s.coins)||0}"><button id="ownerSetCoins">SET 🪙</button></div><div class="owner-input-row"><input id="ownerGemsInput" type="number" min="0" value="${Number(s.gems)||0}"><button id="ownerSetGems">SET 💎</button></div><div class="owner-actions"><button id="ownerAddCoins">+10,000 🪙</button><button id="ownerAddGems">+100 💎</button></div></section>
<section><small>COLLECTION • 7.7.2</small><h3>ROSTER ACCESS</h3><div class="owner-actions stacked"><button id="ownerUnlockFighters">UNLOCK ALL FIGHTERS</button><button id="ownerUnlockSkins">UNLOCK ALL SKINS</button><button id="ownerUnlockGod">UNLOCK THE ONE ABOVE ALL</button></div></section>
<section><small>CAMPAIGN • 7.7.2</small><h3>PROGRESSION</h3><div class="owner-actions stacked"><button id="ownerUnlockCampaign">UNLOCK ALL FIGHTS</button><button id="ownerClearCampaign">MARK ALL CLEARED</button></div></section>
<section><small>SAVE TOOLS • 7.7.2</small><h3>BACKUP / RESTORE</h3><textarea id="ownerSaveBox" spellcheck="false" placeholder="Owner save JSON"></textarea><div class="owner-actions"><button id="ownerExportSave">EXPORT</button><button id="ownerRestoreSave">RESTORE</button></div></section>
</div><div class="owner-warning">v0.9.7.7.2 Owner access is stored locally on this device. This is a development permission layer, not server-side authentication.</div></div></div>`}
function dismissBoard(minimized=false){const o=$('#ownerBoardOverlay');if(!o)return;if(minimized)o.classList.add('owner-board-minimizing');else o.classList.add('owner-board-closing');setTimeout(()=>{o.remove();ensureDock();showDock(true)},minimized?150:120)}
function openBoard(){if(!unlocked())return;injectStyle();ensureDock();$('#ownerBoardOverlay')?.remove();document.body.insertAdjacentHTML('beforeend',boardMarkup());showDock(false);requestAnimationFrame(()=>$('#ownerBoardOverlay')?.classList.add('owner-board-visible'));$('#ownerBoardClose').onclick=()=>dismissBoard(false);$('#ownerBoardMin').onclick=()=>dismissBoard(true);$('#ownerBoardOverlay').addEventListener('click',e=>{if(e.target.id==='ownerBoardOverlay')dismissBoard(true)});
$('#ownerSetCoins').onclick=()=>mutate('Set coin balance',s=>s.coins=Math.max(0,Number($('#ownerCoinsInput').value)||0));
$('#ownerSetGems').onclick=()=>mutate('Set diamond balance',s=>s.gems=Math.max(0,Number($('#ownerGemsInput').value)||0));
$('#ownerAddCoins').onclick=()=>mutate('Add 10,000 coins',s=>s.coins=(Number(s.coins)||0)+10000);
$('#ownerAddGems').onclick=()=>mutate('Add 100 diamonds',s=>s.gems=(Number(s.gems)||0)+100);
$('#ownerUnlockFighters').onclick=()=>mutate('Unlock all fighters',s=>{s.owned=s.owned||{};const live=Object.keys(window.FightArena?.chars||{});(live.length?live:fighters).forEach(n=>s.owned[n]=true)});
$('#ownerUnlockSkins').onclick=()=>mutate('Unlock all current skins',s=>{s.skinsOwned=s.skinsOwned||{};skins.forEach(id=>s.skinsOwned[id]=true)});
$('#ownerUnlockGod').onclick=()=>mutate('Unlock The One Above All',s=>{s.ownerGodUnlocked=true;s.owned=s.owned||{};s.owned['The One Above All']=true});
$('#ownerUnlockCampaign').onclick=()=>mutate('Unlock all campaign fights',s=>{s.unlocked=20});
$('#ownerClearCampaign').onclick=()=>mutate('Mark every campaign fight cleared',s=>{s.unlocked=20;s.campaignWins=s.campaignWins||{};campaign.forEach(n=>s.campaignWins[n]=true);s.campaignPhaseRewards=s.campaignPhaseRewards||{};s.campaignPhaseRewards.prologue=true});
$('#ownerExportSave').onclick=async()=>{const text=JSON.stringify(read(),null,2);$('#ownerSaveBox').value=text;try{await navigator.clipboard.writeText(text);$('#ownerExportSave').textContent='✓ COPIED'}catch{$('#ownerExportSave').textContent='READY'}};
$('#ownerRestoreSave').onclick=()=>{let parsed;try{parsed=JSON.parse($('#ownerSaveBox').value)}catch{return alert('Invalid save JSON.')}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))return alert('Save JSON must be a game-save object.');if(!confirm('Restore this save? This replaces the current local game save.'))return;parsed.ownerBoardUnlocked=true;write(parsed);reloadWith('SAVE RESTORED')};
setTimeout(()=>window.MultiverseArenaOwnerDevTools?.mount?.(),0)}
function flash(){const msg=sessionStorage.getItem('ownerBoardFlash');if(!msg)return;sessionStorage.removeItem('ownerBoardFlash');setTimeout(()=>{const t=$('#toast');if(t){t.textContent='👑 '+msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),1800)}},700)}
function audit(){injectStyle();brand();wireRedeem();ensureSettingsButton();ensureDock()}
function init(){audit();flash();window.MultiverseArenaUpdate09772={version:BUILD,audit,open:openBoard,minimize:()=>dismissBoard(true),unlocked,redeem:redeemOwner}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();addEventListener('fightarena-ready',()=>setTimeout(audit,500));addEventListener('pageshow',()=>setTimeout(audit,0));
})();
