/* Multiverse Arena v0.9.7.7 — Hero Update + Bug Fixes */
(()=>{
'use strict';
const BUILD='0.9.7.7',ASSET='0977',$=(s,r=document)=>r.querySelector(s);let wired=false;
function style(){if($('#update0977Style'))return;const l=document.createElement('link');l.id='update0977Style';l.rel='stylesheet';l.href=`update-v0977.css?v=${ASSET}`;document.head.appendChild(l)}
function brand(){document.title='Multiverse Arena v0.9.7.7 — Hero Update + Bug Fixes';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.7');const u=$('#updates');if(u)u.textContent='UPDATE LOG  •  v0.9.7.7';const latest=$('.latest-stat');if(latest){const b=$('b',latest),s=$('span',latest);if(b)b.textContent='v0.9.7.7';if(s)s.textContent='Thor • Doctor Strange • Star-Lord • Mobile + Training Fixes'}const h=$('.build-health b');if(h)h.textContent='v0.9.7.7 • HERO UPDATE • STABLE';const c=$('#deviceChooser .eyebrow');if(c)c.textContent='MULTIVERSE ARENA • v0.9.7.7';const hero=$('#home .hero-copy');if(hero){const tag=$('.tag',hero),title=$('h1',hero),p=$('p',hero);if(tag)tag.textContent='HERO UPDATE • THREE NEW FIGHTERS';if(title)title.innerHTML='GODS. MAGIC.<br>GALACTIC FIREPOWER.';if(p)p.textContent='Thor, Doctor Strange and Star-Lord join the roster with dedicated combat kits, premium silhouettes and unique animated Specials.'}document.documentElement.dataset.multiverseRelease=BUILD;if(window.MultiverseArenaRuntime){window.MultiverseArenaRuntime.version=BUILD;window.MultiverseArenaRuntime.asset=ASSET}}
function cardState(card){const base=card?.dataset?.fighterName,title=$('h3',card)?.textContent?.trim(),name=base||Object.keys(window.FightArena?.chars||{}).find(n=>n.toUpperCase()===title?.toUpperCase());if(!name)return null;const status=[...card.children].find(n=>n.tagName==='SMALL'&&!n.closest('.fighter-quick-stats-v0973'))?.textContent?.toUpperCase()||'',owned=/OWNED|SELECTED/.test(status);return{name,owned}}
function repairFilters(){const cards=[...document.querySelectorAll('#charCards .rank-fighters-grid>.card')],bar=$('.collection-filter-v0976[data-filter-type="fighters"]');if(!cards.length||!bar)return;cards.forEach(card=>{const s=cardState(card);if(!s)return;card.classList.toggle('collection-locked-v0977',!s.owned);card.dataset.ownedV0977=s.owned?'1':'0'});const active=$('[data-filter].active',bar)?.dataset.filter||'all';let visible=0,ownedCount=0;cards.forEach(card=>{const owned=card.dataset.ownedV0977==='1';if(owned)ownedCount++;const show=active==='all'||active==='owned'&&owned||active==='locked'&&!owned;card.classList.toggle('filter-hidden-v0976',!show);if(show)visible++});const count=$('.collection-filter-count-v0976',bar);if(count)count.textContent=`${visible}/${cards.length} • OWNED ${ownedCount} • 🔒 ${cards.length-ownedCount}`}
function trainingRepair(){const fill=$('#trainingSpecial'),reset=$('#trainingReset');if(fill){fill.onclick=e=>{e.preventDefault();e.stopPropagation();window.FightArenaTrainingControls?.fill?.()}}if(reset){reset.onclick=e=>{e.preventDefault();e.stopPropagation();window.FightArenaTrainingControls?.reset?.()}}}
function phaseRepair(){const tabs=$('#levelCards .gauntlet-phase-tabs-v0966');if(!tabs)return;const active=$('.gauntlet-phase-tab-v0966.active',tabs);if(innerWidth<=700&&active)active.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}
function cleanUpdateLog(){const box=$('#updatesScreen .changelog');if(!box)return;const items=[['⚡','Thor joins the Arena','S Rank Asgardian powerhouse with Mjolnir Throw, Lightning Strike, Thunder Rush and the God of Thunder Special.'],['🔮','Doctor Strange joins the Arena','S Rank control fighter with Eldritch Bolts, Portal Strike, Seraphim Shield and a Mirror Dimension Special.'],['🚀','Star-Lord joins the Arena','A+ Rank ranged mobility fighter with dual Element Blasters, Jet Boot Dash, Gravity Mine and Legendary Outlaw.'],['🎨','Premium Hero Presentation','All three heroes launch with purpose-built silhouettes, signature equipment, bespoke VFX and attack animations rather than placeholder recolors.'],['📱','Phone Phase Selector Fix','Phase tabs now scroll cleanly on narrow phones instead of overlapping. iPad/tablet presentation remains unchanged.'],['🎯','Training Controls Repair','FILL SPECIAL and RESET are rebound directly to the canonical Training API and work across the expanded roster.'],['🔒','Collection Filter Repair','OWNED and LOCKED now use explicit ownership state. Locked fighter cards show a clear lock badge and live roster counts.'],['🧪','Regression Sweep','Boss Protocol, boss-only Diamonds, Rematch, Daily Reward, purchase confirmation, Hulkbuster, Phase Mastery and save compatibility remain protected.']];box.innerHTML=items.map(([i,t,p])=>`<div class="log-item recent-release-v0977"><div class="log-icon">${i}</div><div><b>${t}</b><p>${p}</p></div></div>`).join('');const tag=$('#updatesScreen .panel>.tag');if(tag)tag.textContent='v0.9.7.7 • HERO UPDATE';const title=$('#updatesScreen .panel>h2');if(title)title.textContent='THREE HEROES. THREE NEW PLAYSTYLES.'}
function audit(){style();brand();repairFilters();trainingRepair();phaseRepair()}
function wire(){if(wired)return;wired=true;$('#gallery')?.addEventListener('click',()=>setTimeout(repairFilters,180));$('#charCards')?.addEventListener('click',()=>setTimeout(repairFilters,120));document.querySelectorAll('[data-collection-tab]').forEach(b=>b.addEventListener('click',()=>setTimeout(repairFilters,100)));$('#play')?.addEventListener('click',()=>setTimeout(phaseRepair,220));$('#levelCards')?.addEventListener('click',()=>setTimeout(phaseRepair,80));$('#updates')?.addEventListener('click',()=>setTimeout(()=>{brand();cleanUpdateLog()},40));addEventListener('resize',()=>setTimeout(phaseRepair,80));addEventListener('pageshow',()=>setTimeout(audit,0));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(audit,0)})}
function init(){audit();cleanUpdateLog();wire();window.MultiverseArenaUpdate0977={version:BUILD,audit,repairFilters,trainingRepair,phaseRepair}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();addEventListener('fightarena-ready',()=>setTimeout(init,760),{once:true});
})();
