/* Multiverse Arena v0.9.7.7.2 — Stable Bootstrap + modular migration foundation */
(()=>{
'use strict';
const BUILD='0.9.7.7.2';
const ASSET='09772';
const SAVE_KEY='fightArenaV08';
const CORE='app/core/core-runtime-v0958.js';
const MODULES=['app/config/runtime-manifest.js','app/state/state.js','app/input/input.js','app/characters/characters.js','app/combat/combat.js','app/core/game.js','app/ui/ui.js','app/owner/storage.js','app/owner/commands.js','app/ui/ownerboard.js','app/systems/save.js'];
const FALLBACK_RUNTIME=['device-v092.js','touch-v0941.js','stability-v0941.js','campaign-v097.js','ui-v09571.js','polish-v09572.js','premium-v096.js','update-v0962.js','update-v0963.js','update-v0964.js','update-v097.js','update-v0971.js','update-v0972.js','update-v0973.js','update-v0974.js','update-v09741.js','update-v0975.js','update-v09751.js','update-v0976.js','update-v09761.js','update-v0977.js','update-v09771.js','update-v09772.js','owner-devtools-v09772.js'];
const state={version:BUILD,asset:ASSET,saveKey:SAVE_KEY,coreArtifact:CORE,moduleFoundation:'0.9.7.7.5-dev',modules:MODULES.slice(),status:'booting',loaded:[],failed:[],runtime:[]};window.MultiverseArenaRuntime=state;
const src=path=>`${path}?v=${ASSET}`;
function script(path){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src(path);s.async=false;s.dataset.coreBoot=BUILD;s.onload=()=>{state.loaded.push(path);resolve(path)};s.onerror=()=>{state.failed.push(path);reject(new Error('Failed to load '+path))};document.body.appendChild(s)})}
function waitFor(test,timeout,label){return new Promise((resolve,reject)=>{const started=Date.now();const check=()=>{let value=false;try{value=test()}catch{}if(value)return resolve(value);if(Date.now()-started>=timeout)return reject(new Error(label+' readiness timeout'));setTimeout(check,30)};check()})}
function brand(){document.title='Multiverse Arena v0.9.7.7.2';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.7.2');const h=document.querySelector('.build-health b');if(h)h.textContent='v0.9.7.7.2 • DEV ARCHITECTURE';const c=document.querySelector('#deviceChooser .eyebrow');if(c)c.textContent='MULTIVERSE ARENA • DEV'}
function fatal(err){state.status='error';console.error('[Multiverse Arena bootstrap]',err);const h=document.querySelector('.build-health b');if(h)h.textContent='DEV • CORE LOAD ERROR'}
function validateModules(){const m=window.MultiverseArenaModules;const missing=['runtimeManifest','state','input','characters','combat','game','ui','ownerStorage','ownerCommands','ownerboard','save'].filter(name=>!m?.[name]);if(missing.length){state.status='warning';state.moduleMissing=missing;console.warn('[modular foundation] missing modules',missing);return false}state.moduleReady=true;return true}
function validateReady(){const missing=[];if(window.FightArena?.version!=='0.9.5.7')missing.push('FightArena core');if(!window.FightArenaTrainingControls)missing.push('training');if(!window.FightArenaDailyControls)missing.push('daily');if(!window.FightArenaCampaignV097)missing.push('campaign');if(!window.MultiverseArenaUpdate09772)missing.push('runtime');if(!window.MultiverseArenaOwnerDevTools)missing.push('owner dev tools');validateModules();if(missing.length){state.status='warning';state.missing=missing}else if(state.moduleReady)state.status='ready';setTimeout(()=>{brand();window.MultiverseArenaUpdate09772?.audit?.()},300)}window.addEventListener('fightarena-ready',validateReady,{once:true});
async function boot(){try{brand();await script(CORE);for(const f of MODULES)await script(f);if(window.FightArena?.version!=='0.9.5.7')throw new Error('canonical core version mismatch');const runtime=window.MultiverseArenaModules?.runtimeManifest?.ordered||FALLBACK_RUNTIME;state.runtime=runtime.slice();for(const f of runtime)await script(f);await waitFor(()=>window.MultiverseArenaUpdate09772&&window.MultiverseArenaOwnerDevTools&&window.MultiverseArenaModules?.ownerStorage&&window.MultiverseArenaModules?.ownerCommands&&window.MultiverseArenaModules?.ownerboard,5000,'dev runtime');window.dispatchEvent(new Event('fightarena-ready'));setTimeout(()=>{if(state.status==='booting')validateReady()},500)}catch(err){fatal(err)}}boot();
})();