/* Multiverse Arena v0.9.7.7 — Hero Update + Bug Fixes Bootstrap */
(()=>{
'use strict';
const BUILD='0.9.7.7';
const ASSET='0977';
const SAVE_KEY='fightArenaV08';
const CORE='app/core/core-runtime-v0958.js';
const RUNTIME=['device-v092.js','touch-v0941.js','stability-v0941.js','campaign-v097.js','ui-v09571.js','polish-v09572.js','premium-v096.js','update-v0962.js','update-v0963.js','update-v0964.js','update-v097.js','update-v0971.js','update-v0972.js','update-v0973.js','update-v0974.js','update-v09741.js','update-v0975.js','update-v09751.js','update-v0976.js','update-v09761.js','update-v0977.js'];
const state={version:BUILD,asset:ASSET,saveKey:SAVE_KEY,coreArtifact:CORE,status:'booting',loaded:[],failed:[],runtime:RUNTIME.slice()};window.MultiverseArenaRuntime=state;
const src=path=>`${path}?v=${ASSET}`;function script(path){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src(path);s.async=false;s.dataset.coreBoot=BUILD;s.onload=()=>{state.loaded.push(path);resolve(path)};s.onerror=()=>{state.failed.push(path);reject(new Error('Failed to load '+path))};document.body.appendChild(s)})}function waitFor(test,timeout,label){return new Promise((resolve,reject)=>{const started=Date.now();const check=()=>{let value=false;try{value=test()}catch{}if(value)return resolve(value);if(Date.now()-started>=timeout)return reject(new Error(label+' readiness timeout'));setTimeout(check,30)};check()})}
function brand(){document.title='Multiverse Arena v0.9.7.7 — Hero Update + Bug Fixes';document.querySelectorAll('.brand .tag').forEach(x=>x.textContent='v0.9.7.7');const u=document.getElementById('updates');if(u)u.textContent='UPDATE LOG  •  v0.9.7.7';const latest=document.querySelector('.latest-stat');if(latest){const b=latest.querySelector('b'),s=latest.querySelector('span');if(b)b.textContent='v0.9.7.7';if(s)s.textContent='Thor • Doctor Strange • Star-Lord • Bug Fixes'}const h=document.querySelector('.build-health b');if(h)h.textContent='v0.9.7.7 • HERO UPDATE • STABLE';const c=document.querySelector('#deviceChooser .eyebrow');if(c)c.textContent='MULTIVERSE ARENA • v0.9.7.7'}
function fatal(err){state.status='error';console.error('[Multiverse Arena v0.9.7.7 bootstrap]',err);const h=document.querySelector('.build-health b');if(h)h.textContent='v0.9.7.7 • CORE LOAD ERROR'}
function validateReady(){const missing=[];if(window.FightArena?.version!=='0.9.5.7')missing.push('FightArena core');if(!window.FightArenaTrainingControls)missing.push('training');if(!window.FightArenaDailyControls)missing.push('daily');if(!window.FightArenaCampaignV097)missing.push('campaign');if(!window.MultiverseArenaUpdate0975)missing.push('purchase confirmation');if(!window.MultiverseArenaUpdate09761)missing.push('interface repair');if(!window.MultiverseArenaUpdate0977)missing.push('hero update');if(!window.FightArenaNameControls)missing.push('skin identity');for(const hero of ['Thor','Doctor Strange','Star-Lord'])if(!window.FightArena?.chars?.[hero])missing.push(hero);if(missing.length){state.status='warning';state.missing=missing;console.warn('[v0.9.7.7 rebuild] missing runtime pieces',missing)}else state.status='ready';setTimeout(()=>{brand();window.MultiverseArenaUpdate0977?.audit?.()},300)}window.addEventListener('fightarena-ready',validateReady,{once:true});
async function boot(){try{brand();await script(CORE);if(window.FightArena?.version!=='0.9.5.7')throw new Error('canonical core version mismatch');for(const f of RUNTIME)await script(f);await waitFor(()=>window.MultiverseArenaUpdate0977&&window.FightArenaTrainingControls&&window.FightArena?.chars?.Thor&&window.FightArena?.chars?.['Doctor Strange']&&window.FightArena?.chars?.['Star-Lord'],5000,'v0.9.7.7 Hero Update');window.dispatchEvent(new Event('fightarena-ready'));setTimeout(()=>{if(state.status==='booting')validateReady()},500)}catch(err){fatal(err)}}boot();
})();
